### ISSUE TITLE
[2021-04-22] NAACL 2021 review 

### ISSUE THREAD

**Issue by inmoonlight** [inmoonlight/yajatime#8]
- https://2021.naacl.org/program/tutorials/

**Comment by jshin49** [comment]
Paper list?

**Comment by moon1ite** [comment]
@jshin49 아직 억셉 페이퍼 리스트가 뜨진 않았는데 아는 것들 위주로 아름아름 모아볼까요

**Comment by moon1ite** [comment]
- https://2021.naacl.org/program/accepted/

**Comment by moon1ite** [comment]
### Case Study: Deontological Ethics in NLP
- Shrimai Prabhumoye, Brendon Boldt, Ruslan Salakhutdinov, Alan W Black
- CMU
- https://arxiv.org/abs/2010.04658

**Comment by moon1ite** [comment]
### Accepted paper list + arxiv
- https://docs.google.com/spreadsheets/d/1__pj0_Ba0j4slpaHt0VfWznpWytBGZcVbCEaNnKB7gE/edit#gid=1813879186
