### ISSUE TITLE
[2021-04-15] 이환희

### ISSUE THREAD

**Issue by moon1ite** [inmoonlight/yajatime#9]
### KPQA: A Metric for Generative Question Answering Using Keyphrase Weights

In the automatic evaluation of generative question answering (GenQA) systems, it is difficult to assess the correctness of generated answers due to the free-form of the answer. Moreover, there is a lack of benchmark datasets to evaluate the suitability of existing metrics in terms of correctness. To study a better metric for GenQA, we first create high-quality human judgments of correctness on two standard GenQA datasets. Using our human-evaluation datasets, we show that widely used n-gram similarity metrics do not correlate with human judgments. To alleviate this problem, we propose a new metric for evaluating the correctness of GenQA. Specifically, our new metric assigns different weights to each token via keyphrase prediction, thereby judging whether a generated answer sentence captures the key meaning of the reference answer. Our proposed metric shows a significantly higher correlation with human judgments than existing metrics in various datasets.

- https://arxiv.org/abs/2005.00192

**Comment by moon1ite** [comment]
- https://scholar.google.com/citations?hl=en&user=eRM8zHkAAAAJ&view_op=list_works&sortby=pubdate

**Comment by hwanheelee1993** [comment]
NAACL 논문 Camera Ready 버전 링크입니다. 
- http://milab.snu.ac.kr/pub/NAACL2021Lee.pdf
